var VARS = {
	NOMBRE_APP: "Control Labores Cayaltí",
	NOMBRE_STORAGE : "DATA_NAV__APPCAYALTILABORES",
	NOMBRE_STORAGE_FECHA_TRABAJO : "DATA_NAV__APP_FECHA_CAYALTILABORES",
	SERVER : "http://216.55.141.11:6060/cayaltiservernisira",
	SIM : {}
};